/**
@file
@brief autogenerated file using all headers
@warning AUTOGENERATED FILE! All changes will be overwritten!
@author Donald Kline, Jr
*/
#ifndef _PRES_SIMULATOR_AUTOGENERATED_FAULT_MAP_HEADER_H__
#define _PRES_SIMULATOR_AUTOGENERATED_FAULT_MAP_HEADER_H__


#include "../utils/PresSubConfig.h"
#include "../utils/FaultMap.h"
#include "EmptyFMap.h"
#include "Basic3f_fmap.h"

namespace PresSim {



/**
@fn PRES_FACTORY_create_fault_map(const PresSubConfig& psc)
@brief Autogenerated function to automatically import and use new fault maps
@warning AUTOGENERATED FUNCTION! All changes will be overwritten
*/
unique_ptr<FaultMap> PRES_FACTORY_create_fault_map(const PresSubConfig& psc)
{
	if (psc.get_name()=="EmptyFMap") {
		std::unique_ptr<FaultMap> csPtr(new EmptyFMap(psc));
		return csPtr;
	}
	if (psc.get_name()=="Basic3f_fmap") {
		std::unique_ptr<FaultMap> csPtr(new Basic3f_fmap(psc));
		return csPtr;
	}
	if (psc.get_name()==NULL_STR_PRES) {
		std::unique_ptr<FaultMap> csPtr(new EmptyFMap(psc));
		return csPtr;
	}
	PRES_ERROR("Invalid FaultMap: "+psc.get_name());
	abort();
}

}

#endif
